name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Create deployment package
      run: |
        mkdir -p deploy_package
        
        # Copy built frontend
        cp -r dist/* deploy_package/
        
        # Copy server files (if needed for static hosting)
        # cp -r server deploy_package/
        
        # Create route files for app access
        cat > deploy_package/onboarding.html << 'EOF'
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Assessment - The Back Coach</title><style>body{margin:0;font-family:system-ui;background:#000;color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center}.box{text-align:center;max-width:400px;padding:2rem}h1{font-size:2.5rem;font-weight:900;color:#16a34a;margin-bottom:1rem}.ok{background:rgba(22,163,74,0.1);border:2px solid #16a34a;padding:1rem;border-radius:8px;margin:1rem 0}p{font-size:1.1rem;margin:0.5rem 0}.btn{background:#16a34a;color:#fff;padding:1rem 1.5rem;border:none;border-radius:6px;text-decoration:none;display:inline-block;margin-top:1rem}</style></head><body><div class="box"><h1>Assessment Ready!</h1><div class="ok"><p><strong>✅ Auto-deployed successfully</strong></p></div><a class="btn" href="https://thebackcoach--5000--f41e2e86-6b1e-4e60-b81f-ac2c5beee3fc.repl.co/onboarding">Continue to Full App</a></div></body></html>
EOF
        
        cat > deploy_package/splash.html << 'EOF'
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Welcome - The Back Coach</title><style>body{margin:0;font-family:system-ui;background:#000;color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center}.box{text-align:center;max-width:400px;padding:2rem}h1{font-size:2.5rem;font-weight:900;color:#16a34a;margin-bottom:1rem}.ok{background:rgba(22,163,74,0.1);border:2px solid #16a34a;padding:1rem;border-radius:8px;margin:1rem 0}p{font-size:1.1rem;margin:0.5rem 0}.btn{background:#16a34a;color:#fff;padding:1rem 1.5rem;border:none;border-radius:6px;text-decoration:none;display:inline-block;margin-top:1rem}</style></head><body><div class="box"><h1>Welcome!</h1><div class="ok"><p><strong>✅ Auto-deployed successfully</strong></p></div><a class="btn" href="https://thebackcoach--5000--f41e2e86-6b1e-4e60-b81f-ac2c5beee3fc.repl.co/splash">Continue to Full App</a></div></body></html>
EOF
        
        # Create .htaccess for routing
        cat > deploy_package/.htaccess << 'EOF'
RewriteEngine On
RewriteBase /

# App routes
RewriteRule ^onboarding/?$ onboarding.html [L]
RewriteRule ^splash/?$ splash.html [L]

# SPA routing for built app
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
EOF
        
        # Add deployment timestamp
        echo "Deployed: $(date)" > deploy_package/last-deploy.txt
        
        ls -la deploy_package/
    
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy_package/
        server-dir: /public_html/
        timeout: 300000
        security: loose
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
