name: Deploy App Routes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create app with routing
      run: |
        mkdir -p dist
        
        # Create index.html that handles all routes
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>The Back Coach</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
              background: #000; color: #fff; min-height: 100vh;
              display: flex; align-items: center; justify-content: center;
            }
            .container { text-align: center; max-width: 600px; padding: 2rem; }
            h1 { font-size: 3rem; margin-bottom: 1rem; font-weight: 900; }
            .status { background: rgba(22,163,74,0.1); border: 1px solid #16a34a; 
                     padding: 1rem; border-radius: 12px; margin: 2rem 0; }
            .route { color: #16a34a; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1 id="title">The Back Coach</h1>
            <div class="status">
              <p>Route: <span class="route" id="path"></span></p>
              <p id="status">Routes working! Redirecting to app...</p>
            </div>
          </div>
          <script>
            const path = window.location.pathname;
            document.getElementById('path').textContent = path;
            
            if (path === '/onboarding') {
              document.getElementById('title').textContent = 'Assessment Ready';
              document.getElementById('status').textContent = '/onboarding route working!';
            } else if (path === '/splash') {
              document.getElementById('title').textContent = 'Welcome Screen';
              document.getElementById('status').textContent = '/splash route working!';
            }
            
            setTimeout(() => {
              window.location.href = 'https://thebackcoach--5000--f41e2e86-6b1e-4e60-b81f-ac2c5beee3fc.repl.co' + path;
            }, 2000);
          </script>
        </body>
        </html>
        EOF
    
    - name: Deploy with override
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
        dangerous-clean-slate: true
