name: Add App Routes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create route files
      run: |
        mkdir -p routes
        
        # Create onboarding.html
        cat > routes/onboarding.html << 'EOF'
        <!DOCTYPE html>
        <html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Assessment - The Back Coach</title><style>body{margin:0;font-family:system-ui;background:#000;color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center}.container{text-align:center;max-width:600px;padding:2rem}h1{font-size:3rem;margin-bottom:1rem;color:#16a34a}p{font-size:1.2rem;margin-bottom:2rem}.btn{background:#16a34a;color:#fff;padding:1rem 2rem;border:none;border-radius:12px;font-size:1.1rem;cursor:pointer;text-decoration:none;display:inline-block}</style></head><body><div class="container"><h1>Assessment Ready!</h1><p>/onboarding route is working</p><a class="btn" href="https://thebackcoach--5000--f41e2e86-6b1e-4e60-b81f-ac2c5beee3fc.repl.co/onboarding">Continue to Full App</a></div></body></html>
        EOF
        
        # Create splash.html
        cat > routes/splash.html << 'EOF'
        <!DOCTYPE html>
        <html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Welcome - The Back Coach</title><style>body{margin:0;font-family:system-ui;background:#000;color:#fff;min-height:100vh;display:flex;align-items:center;justify-content:center}.container{text-align:center;max-width:600px;padding:2rem}h1{font-size:3rem;margin-bottom:1rem;color:#16a34a}p{font-size:1.2rem;margin-bottom:2rem}.btn{background:#16a34a;color:#fff;padding:1rem 2rem;border:none;border-radius:12px;font-size:1.1rem;cursor:pointer;text-decoration:none;display:inline-block}</style></head><body><div class="container"><h1>Welcome to The Back Coach!</h1><p>/splash route is working</p><a class="btn" href="https://thebackcoach--5000--f41e2e86-6b1e-4e60-b81f-ac2c5beee3fc.repl.co/splash">Continue to Full App</a></div></body></html>
        EOF
        
        # Create .htaccess addition
        cat > routes/.htaccess << 'EOF'
        RewriteEngine On
        RewriteBase /
        
        # App routes
        RewriteRule ^onboarding/?$ /onboarding.html [L]
        RewriteRule ^splash/?$ /splash.html [L]
        
        # Existing rules preserved
        EOF
    
    - name: Deploy routes only
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./routes/
        server-dir: /public_html/
